"""Adicionar status recebido em receitas

Revision ID: ca4eddfeae2e
Revises: fb87c6457807
Create Date: 2026-07-12 17:06:41.184408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4eddfeae2e'
down_revision = 'fb87c6457807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recebido', sa.Boolean(), nullable=True))
    op.execute("UPDATE receitas SET recebido = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receitas', schema=None) as batch_op:
        batch_op.drop_column('recebido')

    # ### end Alembic commands ###
